# -*- coding: utf-8 -*-
from PyQt5 import QtCore
from PyQt5 import QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.resize(695, 383)
        MainWindow.setWindowTitle('Desay 6mm/UPAD 2.6mm test pattern control')
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName('centralwidget')

        MainWindow.setCentralWidget(self.centralwidget)
        self._setup_menu_bar(MainWindow)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName('statusbar')
        MainWindow.setStatusBar(self.statusbar)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self._set_tab_order(MainWindow)

    def _setup_menu_bar(self, MainWindow):
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 695, 20))
        self.menubar.setObjectName('menubar')
        MainWindow.setMenuBar(self.menubar)

    def _create_brightness_block(self):
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(290, 50, 400, 260))
        self.horizontalLayoutWidget.setObjectName('horizontalLayoutWidget')
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.sldr_brightness = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.sldr_brightness.setMinimumSize(QtCore.QSize(40, 0))
        self.sldr_brightness.setMaximum(255)
        self.sldr_brightness.setProperty('value', 255)
        self.sldr_brightness.setOrientation(QtCore.Qt.Vertical)
        self.sldr_brightness.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.sldr_brightness.setTickInterval(10)
        self.sldr_brightness.setObjectName('sldr_brightness')
        self.horizontalLayout.addWidget(self.sldr_brightness)

        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.verticalLayoutWidget_3.setMaximumHeight(50)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.horizontalLayout.addWidget(self.verticalLayoutWidget_3)
        self.lbl_brightness = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lbl_brightness.setText('Brightness:')
        self.lbl_brightness.setObjectName('lbl_brightness')
        self.verticalLayout_3.addWidget(self.lbl_brightness)
        self.lbl_brightness_val = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lbl_brightness_val.setText('Unknown')
        self.lbl_brightness_val.setObjectName('lbl_brightness_val')
        self.verticalLayout_3.addWidget(self.lbl_brightness_val)

    def _create_serial_port_block(self):
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 50, 240, 241))
        self.verticalLayoutWidget_2.setObjectName('verticalLayoutWidget_2')
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.lbl_select_port = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_select_port.setText('Select port connected to controller:')
        self.lbl_select_port.setObjectName('lbl_select_port')
        self.verticalLayout_2.addWidget(self.lbl_select_port)
        self.lst_serial_ports = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.lst_serial_ports.setObjectName('lst_serial_ports')
        self.lst_serial_ports.setToolTip('Port (vendor, model)')
        # self.lst_serial_ports.setSortingEnabled(True)  # TODO:check if this interferes with order
        self.verticalLayout_2.addWidget(self.lst_serial_ports)
        self.btn_serial_open = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_serial_open.setText('Click to open selected port')
        self.btn_serial_open.setCheckable(True)
        self.btn_serial_open.setObjectName('btn_serial_open')
        self.verticalLayout_2.addWidget(self.btn_serial_open)
        self.btn_serial_refresh = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_serial_refresh.setText('Refresh ports list')
        self.btn_serial_refresh.setObjectName('btn_serial_refresh')
        self.verticalLayout_2.addWidget(self.btn_serial_refresh)
        self.lbl_serial_status = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_serial_status.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_serial_status.setText('No port')
        self.lbl_serial_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_serial_status.setObjectName('lbl_serial_status')
        self.lbl_serial_status.setStyleSheet('background-color:orange')
        self.verticalLayout_2.addWidget(self.lbl_serial_status)

        self.lbl_output_port = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_output_port.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_output_port.setObjectName('lbl_output_port')
        self.verticalLayout_2.addWidget(self.lbl_output_port)
        self.cmb_output = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.cmb_output.setEditable(False)
        self.cmb_output.setToolTip('Select which output screen is connected to')
        self.cmb_output.setObjectName('cmb_output')
        self.lbl_output_port.setText('Screen connected to:')
        self.cmb_output.addItems(['No screen', 'Output 1', 'Output 2'])
        self.cmb_output.setCurrentIndex(0)
        self.verticalLayout_2.addWidget(self.cmb_output)

    def _set_tab_order(self, MainWindow):
        MainWindow.setTabOrder(self.btn_normal, self.btn_red)
        MainWindow.setTabOrder(self.btn_red, self.btn_green)
        MainWindow.setTabOrder(self.btn_green, self.btn_blue)
        MainWindow.setTabOrder(self.btn_blue, self.btn_white)
        MainWindow.setTabOrder(self.btn_white, self.btn_slash)
        MainWindow.setTabOrder(self.btn_slash, self.btn_blackout)
        MainWindow.setTabOrder(self.btn_blackout, self.btn_freeze)
        MainWindow.setTabOrder(self.btn_freeze, self.btn_serial_refresh)
        MainWindow.setTabOrder(self.btn_serial_refresh, self.cmb_output)
        MainWindow.setTabOrder(self.cmb_output, self.btn_serial_open)
        MainWindow.setTabOrder(self.btn_serial_open, self.lst_serial_ports)
        MainWindow.setTabOrder(self.lst_serial_ports, self.sldr_brightness)

    def _create_pattern_block(self):
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(490, 60, 160, 233))
        self.verticalLayoutWidget.setObjectName('verticalLayoutWidget')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName('verticalLayout')
        self.lbl_input_pattern = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_input_pattern.setText('Input/pattern:')
        self.lbl_input_pattern.setObjectName('lbl_input_pattern')
        self.verticalLayout.addWidget(self.lbl_input_pattern)
        self.btn_normal = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.btn_normal.setText('Live (input)')
        self.btn_normal.setObjectName('btn_normal')
        self.verticalLayout.addWidget(self.btn_normal)
        self.btn_red = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.btn_red.setText('Red')
        self.btn_red.setObjectName('btn_red')
        self.verticalLayout.addWidget(self.btn_red)
        self.btn_green = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.btn_green.setText('Green')
        self.btn_green.setObjectName('btn_green')
        self.verticalLayout.addWidget(self.btn_green)
        self.btn_blue = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.btn_blue.setText('Blue')
        self.btn_blue.setObjectName('btn_blue')
        self.verticalLayout.addWidget(self.btn_blue)
        self.btn_white = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.btn_white.setText('White')
        self.btn_white.setObjectName('btn_white')
        self.verticalLayout.addWidget(self.btn_white)
        self.btn_slash = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.btn_slash.setText('Slash')
        self.btn_slash.setObjectName('btn_slash')
        self.verticalLayout.addWidget(self.btn_slash)
        self.btn_blackout = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.btn_blackout.setText('Blackout')
        self.btn_blackout.setObjectName('btn_blackout')
        self.verticalLayout.addWidget(self.btn_blackout)
        self.btn_freeze = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.btn_freeze.setText('Freeze')
        self.btn_freeze.setObjectName('btn_freeze')
        self.verticalLayout.addWidget(self.btn_freeze)
